/*
 * Copyright (C) 2010 Xfce Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

/*
 * THIS FILE IS AUTOMATICALLY GENERATED BY http://translations.xfce.org
 * DO NOT EDIT IT MANUALLY!
 */

#include <gtk/gtk.h>
#include <libxfce4util/libxfce4util.h>

#define TRANSLATORS_H_STAMP "2013-05-12 00:21:13"
#define ATSIGN "@"
#define DOTSIGN "."

typedef struct
{
  const gchar *name;
  const gchar *email;
  guint        is_coordinator : 1;
}
TranslatorInfo;

typedef struct
{
  const gchar          *name;
  const gchar          *code;
  const TranslatorInfo *members;
}
TranslatorTeam;

static const TranslatorInfo xfce_translators_am[] =
{
  { "Tegegne Tefera", "tefera" ATSIGN "mekuria" DOTSIGN "com", TRUE },
  { "BelayTekalign", "BelayTekalign" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Fantaw Tesema", "fantaw" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ar[] =
{
  { "M" DOTSIGN "hanny sabbagh", "hannysabbagh" ATSIGN "hotmail" DOTSIGN "com", TRUE },
  { "كريم أولاد الشلحة", "herr" DOTSIGN "linux88" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "محمد الحرقان", "malham1" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "abdilra7eem", "abdilra7eem" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "Amine", "med" ATSIGN "mailoo" DOTSIGN "org", FALSE },
  { "khire aldin kajjan", "Cransh" DOTSIGN "t2" ATSIGN "hotmail" DOTSIGN "com", FALSE },
  { "Hasen il Judy", "hasan" DOTSIGN "aljudy" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "mohsen", "linuxer9" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Noureddin Khatat", "noureddin" ATSIGN "barid" DOTSIGN "com", FALSE },
  { "os_", "syriatalks" ATSIGN "hotmail" DOTSIGN "com", FALSE },
  { "sanad", "0sanad0" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Yassine Bouhadi", "yassine" DOTSIGN "skiloo" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "ybanafa", "ybanafa" ATSIGN "alasersystems" DOTSIGN "com", FALSE },
  { "yusuf", "ys9889" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ast[] =
{
  { "Iñigo Varela", "malditoastur" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_be[] =
{
  { "Andrej Zakharevich", "andrej" ATSIGN "zahar" DOTSIGN "ws", TRUE },
  { "Anton Barycheuski", "antofa1" ATSIGN "mail" DOTSIGN "ru", FALSE },
  { "Arthur Schebetau", "archisoft6" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "belarus", "useq" ATSIGN "list" DOTSIGN "ru", FALSE },
  { "Юрый Кашчэеў", "kashcheyeu" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "Mikalai Udodau", "crom-a" ATSIGN "tut" DOTSIGN "by", FALSE },
  { "Mike Gelfand", "mikedld" ATSIGN "mikedld" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_bg[] =
{
  { "Valentin Tunev", "hdbuster" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Kiril Kirilov", "cybercop_montana" ATSIGN "abv" DOTSIGN "bg", FALSE },
  { "Milen Milev", "fanfolet" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ognyan Kulev", "ogi" ATSIGN "tower" DOTSIGN "3" DOTSIGN "bg", FALSE },
  { "sahwar", "ve4ernik" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Dimitar Dimitrov", "insidepower" ATSIGN "abv" DOTSIGN "bg", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_bn[] =
{
  { "Jamil Ahmed", "itsjamil" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_bn_IN[] =
{
  { "Runa Bhattacharjee", "runabh" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Dipjyoti Ghosh", "dipjyoti" DOTSIGN "ghosh" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sankarshan Mukhopadhyay", "sankarshan" ATSIGN "randomink" DOTSIGN "org", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ca[] =
{
  { "Carles Muñoz Gorriz", "carlesmu" ATSIGN "internautas" DOTSIGN "org", TRUE },
  { "Paul Garden", "kiari62" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Joan Montané", "joan" ATSIGN "montane" DOTSIGN "cat", FALSE },
  { "Jordi Deu-Pons", "jordi" ATSIGN "jordeu" DOTSIGN "net", FALSE },
  { "Jordi Clariana", "jordiclariana" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Roger Pueyo Centelles", "xfce" ATSIGN "rogerpueyo" DOTSIGN "com", FALSE },
  { "Harald Servat", "redcrash" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Marc Pastor Sanz", "sandandmercury" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Xan", "xancorreu" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_cs[] =
{
  { "David Štancl", "dstancl" ATSIGN "dstancl" DOTSIGN "cz", TRUE },
  { "Michal Várady", "miko" DOTSIGN "vaji" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Miro Hrončok", "miro" ATSIGN "hroncok" DOTSIGN "cz", FALSE },
  { "Jakub Špirk", "spirk" DOTSIGN "jakub" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_da[] =
{
  { "Per Kongstad", "p_kongstad" ATSIGN "op" DOTSIGN "pl", TRUE },
  { "Aputsiaq Janussen", "aj" ATSIGN "isit" DOTSIGN "gl", FALSE },
  { "Kris Thomsen", "mail" ATSIGN "kristhomsen" DOTSIGN "dk", FALSE },
  { "Morten Juhl-Johansen Zölde-Fejér", "mjjzf" ATSIGN "syntaktisk" DOTSIGN "dk", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_de[] =
{
  { "Christoph Wickert", "christoph" DOTSIGN "wickert" ATSIGN "googlemail" DOTSIGN "com", TRUE },
  { "Andreas Kamzol", "andreas" DOTSIGN "kamzol" ATSIGN "googlemail" DOTSIGN "com", FALSE },
  { "Christoph Mende", "angelos" ATSIGN "gentoo" DOTSIGN "org", FALSE },
  { "Michael Spahn", "any0n3" ATSIGN "fedoraproject" DOTSIGN "org", FALSE },
  { "Josef Radinger", "cheese" ATSIGN "nosuchhost" DOTSIGN "net", FALSE },
  { "Chris Leick", "c" DOTSIGN "leick" ATSIGN "vollbio" DOTSIGN "de", FALSE },
  { "Christian Weiske", "cweiske" ATSIGN "cweiske" DOTSIGN "de", FALSE },
  { "Uwe Krause", "derhorst" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jakob Kramer", "jakob" DOTSIGN "kramer" ATSIGN "gmx" DOTSIGN "de", FALSE },
  { "Johannes Lips", "johannes" DOTSIGN "lips" ATSIGN "googlemail" DOTSIGN "com", FALSE },
  { "Harald Judt", "h" DOTSIGN "judt" ATSIGN "gmx" DOTSIGN "at", FALSE },
  { "Hubert Hesse", "hub" ATSIGN "hubertscorner" DOTSIGN "de", FALSE },
  { "Victoria Ivanova", "ivansvika" ATSIGN "googlemail" DOTSIGN "com", FALSE },
  { "Raphael Groner", "raphgro" ATSIGN "web" DOTSIGN "de", FALSE },
  { "Mario Blättermann", "mario" DOTSIGN "blaettermann" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Mark Trompell", "mark" ATSIGN "foresightlinux" DOTSIGN "org", FALSE },
  { "Matthias Mailänder", "matthias" ATSIGN "mailaender" DOTSIGN "name", FALSE },
  { "Michael Schmitt", "user" DOTSIGN "of" DOTSIGN "xfce" ATSIGN "googlemail" DOTSIGN "com", FALSE },
  { "Simon Steinbeiss", "ochosi" ATSIGN "xfce" DOTSIGN "org", FALSE },
  { "Michael Kogan", "photon89" ATSIGN "googlemail" DOTSIGN "com", FALSE },
  { "Niklas Reinmuth", "Niklas" DOTSIGN "Reinmuth" ATSIGN "googlemail" DOTSIGN "com", FALSE },
  { "Paul Seyfert", "pseyfert" ATSIGN "mathphys" DOTSIGN "fsk" DOTSIGN "uni-heidelberg" DOTSIGN "de", FALSE },
  { "Roland Kübert", "roland" ATSIGN "upic" DOTSIGN "de", FALSE },
  { "Knuth Gurkasch", "knuth" ATSIGN "sinn3r" DOTSIGN "org", FALSE },
  { "Fabian Nowak", "timystery" ATSIGN "arcor" DOTSIGN "de", FALSE },
  { "Detlef Riekenberg", "wine" DOTSIGN "dev" ATSIGN "web" DOTSIGN "de", FALSE },
  { "Raphael Fritz", "teabag" ATSIGN "pofblog" DOTSIGN "de", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_el[] =
{
  { "Evaggelos Balaskas", "ebalaskas" ATSIGN "ebalaskas" DOTSIGN "gr", TRUE },
  { "Stavros Giannouris", "stavrosg" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Constantino Markos", "conmarap" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ioannis Daliakopoulos", "yannis" ATSIGN "farm" DOTSIGN "gr", FALSE },
  { "forfolias", "forfolias" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "gapan", "vlahavas" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "glezos", "glezos" ATSIGN "indifex" DOTSIGN "com", FALSE },
  { "Efstathios Iosifidis", "iefstathios" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jani Kotsionis", "ikotsionis" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Klearchos-Angelos Gkountras", "kleagkou" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Mario Andonoudiou", "supermodmusic" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "ninos", "epninos" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Georgios Stefanakis", "nonviotale" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Spiros Georgaras", "sng" ATSIGN "hellug" DOTSIGN "gr", FALSE },
  { "Basilis Thomopoulos", "kolxoz83" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_en_GB[] =
{
  { "Kevin Beynon", "kevin" ATSIGN "kevinbeynon" DOTSIGN "com", FALSE },
  { "Howard Chan", "smartboyhw" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jeff Bailes", "thepizzaking" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_eo[] =
{
  { "Michael Moroni", "michael" DOTSIGN "moroni" ATSIGN "mailoo" DOTSIGN "org", TRUE },
  { "Dominique Pellé", "dominique" DOTSIGN "pelle" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jakob Pedersen", "jakobp78" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Pierre Vittet", "pierre-vittet" ATSIGN "pvittet" DOTSIGN "com", FALSE },
  { "Urmas D", "davian818" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_es[] =
{
  { "afsanchez93", "", TRUE },
  { "Daniel Durante", "danieldurante" ATSIGN "ymail" DOTSIGN "com", TRUE },
  { "Hoy Tampoco", "treschavales" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Adolfo Jayme Barrientos", "fitoschido" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Francisco Javier Serrador", "fserrador" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jaime Gascon", "jgascon" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "lbazan", "bazanluis20" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "ma7as", "colonizare" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Matias De lellis", "mati86dl" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Eduardo Mayorga Téllez", "mayorgalinux" ATSIGN "fedoraproject" DOTSIGN "org", FALSE },
  { "Octavio Bernal Quiroz", "octavio" DOTSIGN "bernal" DOTSIGN "q" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergio García", "oigres200" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Pablo Roberto Francisco Lezaeta Reyes", "prflr88" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "David Segura Monroy", "davidseg" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "sebikul", "", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_es_AR[] =
{
  { "Diego Augusto Molina", "diegoaugustomolina" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Manuel Fernando Aponte Guzmán", "manuelferchis" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Santiago Quiroga", "santiago" DOTSIGN "j" DOTSIGN "quiroga" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "C" DOTSIGN " Sebastian Biscussi", "sebastian" DOTSIGN "csb" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "vtamara", "vtamara" ATSIGN "pasosdeJesus" DOTSIGN "org", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_et[] =
{
  { "Allar Kiristaja", "aquastus" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_eu[] =
{
  { "Piarres Beobide", "pi" ATSIGN "beobide" DOTSIGN "net", TRUE },
  { "Asier Iturralde Sarasola", "asier" DOTSIGN "iturralde" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_fa[] =
{
  { "anonxero", "anonxero" ATSIGN "linuxmail" DOTSIGN "org", FALSE },
  { "Mehdi Esmaeelpour", "ariarat" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ehsan Akhlaghi", "esnka" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "mahmood mahm0ud", "mahmud" DOTSIGN "tehrani" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "numb", "amir007ag" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "omead", "mehdioa" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "vahid", "vahidfardi2011" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_fi[] =
{
  { "Jari Rahkonen", "jari" DOTSIGN "rahkonen" ATSIGN "pp1" DOTSIGN "inet" DOTSIGN "fi", TRUE },
  { "Flammie Pirinen", "flammie" ATSIGN "iki" DOTSIGN "fi", FALSE },
  { "Jarno Liimatainen", "jarliim" ATSIGN "iki" DOTSIGN "fi", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_fr[] =
{
  { "jc jc1", "jc1" DOTSIGN "quebecos" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Xavier Devlamynck", "magicrhesus" ATSIGN "ouranos" DOTSIGN "be", TRUE },
  { "Mike Massonnet", "mmassonnet" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Durand-Favreau Arnaud", "biginoz" ATSIGN "free" DOTSIGN "fr", FALSE },
  { "Dorian Burihabwa", "dorian" DOTSIGN "burihabwa" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Iliyas Jorio", "inv" DOTSIGN "jorio" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Benoit THIBAUD", "frombenny" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Mario Gervais", "gervais" DOTSIGN "mario" ATSIGN "ymail" DOTSIGN "com", FALSE },
  { "Jérôme Guelfucci", "jeromeg" ATSIGN "xfce" DOTSIGN "org", FALSE },
  { "Jean-Philippe Fleury", "contact" ATSIGN "jpfleury" DOTSIGN "net", FALSE },
  { "Kppqju77", "ju" DOTSIGN "adde" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Yanice lei00", "cherrak" ATSIGN "lavabit" DOTSIGN "com", FALSE },
  { "Jourdain Cyril", "cyril" DOTSIGN "jd" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Louis Moureaux", "m_louis30" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "Maximilian Schleiss", "maximilian" ATSIGN "xfce" DOTSIGN "org", FALSE },
  { "marc doutreloux", "mdoutreloux" ATSIGN "yahoo" DOTSIGN "fr", FALSE },
  { "Nicolas Bidault", "nico_bidault" ATSIGN "yahoo" DOTSIGN "fr", FALSE },
  { "Anthony Jorion", "pingax" ATSIGN "frugalware" DOTSIGN "org", FALSE },
  { "Saïd Bouras", "said" DOTSIGN "bouras" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Steve Dodier", "sidnioulz" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "smonff", "smonff" ATSIGN "lavabit" DOTSIGN "com", FALSE },
  { "Yannick Le Guen", "leguen" DOTSIGN "yannick" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Corentin Noël", "tintou" ATSIGN "mailoo" DOTSIGN "org", FALSE },
  { "Rémi Corti", "remi" DOTSIGN "corti" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_gl[] =
{
  { "mbouzada", "mbouzada" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Leandro Regueiro", "leandro" DOTSIGN "regueiro" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "xirin", "xirin1973" ATSIGN "yahoo" DOTSIGN "es", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_he[] =
{
  { "Nick Schermer", "nick" ATSIGN "xfce" DOTSIGN "org", TRUE },
  { "Hezy Amiel", "open" ATSIGN "hezyamiel" DOTSIGN "com", FALSE },
  { "nick vurgaft", "slipperygate" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_hi[] =
{
  { "Anurag Garg", "ang" DOTSIGN "astronomy" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "chandan kumar", "chandankumar" DOTSIGN "093047" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Dipanjan Das", "saturn" ATSIGN "hotmail" DOTSIGN "co" DOTSIGN "in", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_hr[] =
{
  { "Petar Koretić", "petar" DOTSIGN "koretic" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Ivica Kolić", "ikoli" ATSIGN "yahoo" DOTSIGN "com", TRUE },
  { "Denis Štogl", "denisstogl" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Luka Kelava", "luka" DOTSIGN "kelava2009" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_hu[] =
{
  { "Gabor Kelemen", "kelemeng" ATSIGN "gnome" DOTSIGN "hu", TRUE },
  { "Zelenak Sandor", "nem11nator" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Imre Benedek", "nucleo" ATSIGN "indamail" DOTSIGN "hu", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_hy[] =
{
  { "sssilver", "sssilver" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "imandes", "imandes" ATSIGN "spyurk" DOTSIGN "am", FALSE },
  { "m_hamlet", "contact" ATSIGN "hamletmuradyan" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_id[] =
{
  { "Andhika Padmawan", "andhika" DOTSIGN "padmawan" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Ardjuna", "asyura" DOTSIGN "x" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "rizaldi martaputra", "rizaldi" DOTSIGN "m" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "zaenal1234", "zaenal1234" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_is[] =
{
  { "Sveinn í Felli", "sveinki" ATSIGN "nett" DOTSIGN "is", TRUE },
  { "Kristófer Arnþórsson", "kristoferarnthors" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Theódór S" DOTSIGN " Andrésson", "husgafl" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_it[] =
{
  { "gianluca foddis", "gianluca" DOTSIGN "foddis" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Giuseppe D'Andrea", "cryptstudent" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "alexarit81", "alexarit81" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Leonardo Totaro", "elleti" DOTSIGN "brainvision" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "conte_sty", "enr" DOTSIGN "conte" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Cristian Marchi", "cri" DOTSIGN "penta" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Cristian Cozzolino", "cristiancozzolino" ATSIGN "libero" DOTSIGN "it", FALSE },
  { "Edoardo Maria Elidoro", "edoardo" DOTSIGN "elidoro" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Enrico Polesel", "polesel" ATSIGN "poisson" DOTSIGN "phc" DOTSIGN "unipi" DOTSIGN "it", FALSE },
  { "Federico Antolini", "federicoantolini84" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Francesco Groccia", "frgroccia" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Enrico Bonato", "enrico" DOTSIGN "bonato" DOTSIGN "81" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Lorenzo Turazza", "lorenzo" DOTSIGN "turazza" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "maluc", "incjsp" ATSIGN "yahoo" DOTSIGN "it", FALSE },
  { "Matei Radu", "matei" DOTSIGN "radu" DOTSIGN "92" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "nicola bergonzi", "nicolabergonzi80" ATSIGN "yahoo" DOTSIGN "it", FALSE },
  { "raffahacks", "raffaele" DOTSIGN "tranquillini" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Riccardo Magini", "rcrmgn" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "salvatorexfce", "salvatorexfce" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergio Spinatelli", "eseasonsapp" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ja[] =
{
  { "Masato Hashimoto", "hashimo" ATSIGN "xfce" DOTSIGN "org", TRUE },
  { "Nobuhiro Iwamatsu", "iwamatsu" ATSIGN "nigauri" DOTSIGN "org", TRUE },
  { "Tiago Barros", "burajirugaijin" ATSIGN "yahoo" DOTSIGN "co" DOTSIGN "jp", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ka[] =
{
  { "Beqa Arabuli", "arabulibeqa" ATSIGN "yahoo" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_kk[] =
{
  { "Baurzhan Muftakhidinov", "baurthefirst" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_kn[] =
{
  { "shankar", "prasad" DOTSIGN "mvs" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Vasudev Kamath", "kamathvasudev" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Kiran Basavaraj", "kiranprl" ATSIGN "aol" DOTSIGN "in", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ko[] =
{
  { "Boram Kim", "boramism" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Seong-ho Cho", "darkcircle" DOTSIGN "0426" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "ByungHyun Choi", "byunghyun" DOTSIGN "choi" ATSIGN "live" DOTSIGN "com", FALSE },
  { "Sung Jin Gang", "ujuc" ATSIGN "ujuc" DOTSIGN "kr", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ky[] =
{
  { "Chingis Jumaliev", "chingis091" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_lt[] =
{
  { "Ričardas Vasiulis", "ricardas" DOTSIGN "v" ATSIGN "inbox" DOTSIGN "lt", TRUE },
  { "Tomas Burokevičius", "tomasbur44" ATSIGN "yahoo" DOTSIGN "co" DOTSIGN "uk", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_lv[] =
{
  { "Rihards Prieditis", "rprieditis" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ms[] =
{
  { "megavarnan", "mega_rhujung" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "Mohd" DOTSIGN " Nadzrin Sapari", "terjemah" DOTSIGN "puretech" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_nb[] =
{
  { "Johan Skorild", "x" DOTSIGN "bluebanana" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "takoi", "thomas" DOTSIGN "amland" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Terje Uriansrud", "terje" ATSIGN "uriansrud" DOTSIGN "net", FALSE },
  { "Kevin Brubeck Unhammer", "javkalas" ATSIGN "mm" DOTSIGN "st", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_nl[] =
{
  { "Nick Schermer", "nick" ATSIGN "xfce" DOTSIGN "org", TRUE },
  { "padv", "pascal" DOTSIGN "devuyst" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Pjotr vertaalt", "pjotrvertaalt" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Robin Jacobs", "broederjacobs" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Timo Verbeek", "timoverbeek10" ATSIGN "hotmail" DOTSIGN "com", FALSE },
  { "Vincent Tunru", "projects" ATSIGN "vinnl" DOTSIGN "nl", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_nn[] =
{
  { "Eivind Ødegård", "gingermig" ATSIGN "yahoo" DOTSIGN "no", FALSE },
  { "Kevin Brubeck Unhammer", "javkalas" ATSIGN "mm" DOTSIGN "st", FALSE },
  { "Eskild Hustvedt", "user" ATSIGN "zerodogg" DOTSIGN "org", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_os[] =
{
  { "Soslan Xwybylty", "soslanx" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_pa[] =
{
  { "A S Alam", "apreet" DOTSIGN "alam" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_pl[] =
{
  { "Piotr Sokół", "psokol" ATSIGN "jabster" DOTSIGN "pl", TRUE },
  { "Marcin Romańczuk", "abjsyn" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ewelina Drożańska", "blinqa" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Paweł Drożański", "pawdro" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Kamil Polczak", "elderlinx" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ireneusz Gierlach", "irek" DOTSIGN "gierlach" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "jacek2v", "jacek2v" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jakub Waśko", "javazlaz" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Kamil Konieczka", "klkkzm" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "kolofaza", "kolofaza" ATSIGN "o2" DOTSIGN "pl", FALSE },
  { "Michał Olber", "michal" DOTSIGN "olber" ATSIGN "osworld" DOTSIGN "pl", FALSE },
  { "Piotr Strębski", "strebski" ATSIGN "o2" DOTSIGN "pl", FALSE },
  { "Swift Geek", "swiftgeek" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Tomasz Chudyk", "chudyk" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_pt[] =
{
  { "Nuno Miguel", "nunomgue" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Joel Patrão", "joel" DOTSIGN "patrao" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "skorzen", "bmomartins" ATSIGN "sapo" DOTSIGN "pt", FALSE },
  { "Sergio Marques", "smarquespt" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_pt_BR[] =
{
  { "Michael Martins", "michaelfm21" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Henrique P" DOTSIGN " Machado", "zehrique" ATSIGN "xfce" DOTSIGN "org", TRUE },
  { "André Miranda", "andreldm1989" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Mateus Rodrigues Costa", "charles" DOTSIGN "costar" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Daniel Lara", "daniellarasouza" ATSIGN "yahoo" DOTSIGN "com" DOTSIGN "br", FALSE },
  { "Carlos Fagiani Junior", "fagianijunior" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Frederico Schardong", "frede" DOTSIGN "sch" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jeferson Corrêa", "jeferson" DOTSIGN "correa91" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Job Borges", "jobdiogenes" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jonas agx", "jonas" DOTSIGN "agx" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Joelso Andrade", "kosmofilo" ATSIGN "ymail" DOTSIGN "com", FALSE },
  { "Lucas Campos", "Rmk236" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Michel Boaventura", "michel" DOTSIGN "boaventura" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Neliton Pereira Junior", "nelitonpjr" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Rafael Ferreira", "rafael" DOTSIGN "f" DOTSIGN "f1" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Rafael Neri", "rafepel" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Filipe Rosset", "rosset" DOTSIGN "filipe" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sérgio Cipolla", "secipolla" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "sidneimarques", "sidneimarques" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Tomas Schertel", "tschertel" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "tvieira", "tiago" ATSIGN "tvieira" DOTSIGN "net", FALSE },
  { "Vladimir Melo", "vladimirmelo" DOTSIGN "psi" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "wolner0b", "wolner0b" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ro[] =
{
  { "Mișu Moldovan", "dumol" ATSIGN "xfce" DOTSIGN "org", TRUE },
  { "George Pîrlea", "george" DOTSIGN "pirlea" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Igor Stirbu", "igor" DOTSIGN "stirbu" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "josephine", "", FALSE },
  { "Ionut Ovejanu", "ovejanu" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "strainu", "xfce" ATSIGN "strainu" DOTSIGN "ro", FALSE },
  { "Horia Dutescu", "vladi" DOTSIGN "linux" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Daiana Heinrich", "xdaiana" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ru[] =
{
  { "Dmitrij Smirnov", "other" ATSIGN "igus" DOTSIGN "lv", TRUE },
  { "0leg", "s" ATSIGN "0leg" DOTSIGN "me", FALSE },
  { "Anton Batenev", "antonbatenev" ATSIGN "yandex" DOTSIGN "ru", FALSE },
  { "Alex Z", "ad_user" ATSIGN "lavabit" DOTSIGN "com", FALSE },
  { "Alexandr Boltris", "ua2fgb" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Alexander Yashkin", "alex" DOTSIGN "aspirine" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergey Alyoshin", "alyoshin" DOTSIGN "s" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Artem Zolochevskiy", "artem" DOTSIGN "zolochevskiy" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Roman Azarenko", "x12ozmouse" ATSIGN "ya" DOTSIGN "ru", FALSE },
  { "brdassign", "dmitriy" DOTSIGN "borodiy" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergey Shlyapugin", "shlyapugin" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "dkorzhevin", "dkorzhevin" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Evgeniy Kosov", "eugene" ATSIGN "kosov" DOTSIGN "net", FALSE },
  { "gnulinux", "nazarov-1990" ATSIGN "bk" DOTSIGN "ru", FALSE },
  { "Vlad Vasilev", "lortwer" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Alexander Matveyev", "a" DOTSIGN "s" DOTSIGN "matveyev" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Denis Koryavov", "dkoryavov" ATSIGN "yandex" DOTSIGN "ru", FALSE },
  { "Andres Kovtunos", "kovtunos" ATSIGN "yandex" DOTSIGN "ru", FALSE },
  { "Avgustine McDonald", "crispsandchees" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Roman K" DOTSIGN "", "mrdoctorwho" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Dmitriy Kudryashov", "overmailed" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergiu Mihai", "sergiu" DOTSIGN "mihai" ATSIGN "devlibre" DOTSIGN "net", FALSE },
  { "Sergey Abramkin", "sergey" ATSIGN "abramk" DOTSIGN "in", FALSE },
  { "Leonid Eremin", "pan" DOTSIGN "sandurlay" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergey Davidoff", "shnatsel" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergey Fedoseev", "fedoseev" DOTSIGN "sergey" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Styopa Semenukha", "semenukha" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "ton", "tonawuda" ATSIGN "inbox" DOTSIGN "ru", FALSE },
  { "Urmas D", "davian818" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ivan Nikolaev", "voidexp" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Victor Homyakov", "vkhomyackov" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_si[] =
{
  { "Danishka Navin", "danishka" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Akila Wajirasena", "akila" DOTSIGN "wajirasena" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Anandawardhana", "anandawardhana" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Kalpa Pathum Welivitigoda", "callkalpa" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Prabath Galagamage", "gprabath" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "kasundigital", "kasunindika" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "kpgtharaka", "kpgtharaka" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "rashan", "rashan" DOTSIGN "uoc" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sk[] =
{
  { "Robert Hartl", "hartl" DOTSIGN "robert" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Michal Löffler", "lofflermichalloffler" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Peter Bubelíny", "p" DOTSIGN "bubeliny" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "ecube", "machava" DOTSIGN "b" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Marek Hlava", "headsvk" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "komunista", "linux" ATSIGN "slavino" DOTSIGN "sk", FALSE },
  { "Tomáš Vadina", "kyberdev" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "prescott", "prescott66" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Tomáš Fedaš", "fedas" DOTSIGN "tomas" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Vladimír Šebo", "vladimir" DOTSIGN "sebo" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sl[] =
{
  { "Gašper Tomažič", "gasper" ATSIGN "gmx" DOTSIGN "com", FALSE },
  { "Nenad Latinović", "nenadlatinovic" ATSIGN "lavabit" DOTSIGN "com", FALSE },
  { "Klemen Košir", "klemen913" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Uros Preloznik", "uros00" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sq[] =
{
  { "Besnik Bleta", "besnik" ATSIGN "programeshqip" DOTSIGN "org", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sr[] =
{
  { "Дејан Васиљевић", "dekibgd" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Milan Stojakov", "koleramilan" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Мирослав Николић", "miroslavnikolic" ATSIGN "rocketmail" DOTSIGN "com", FALSE },
  { "mpopovic", "gpopac" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Nikola Milosavljevic", "minikola" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Саша Петровић", "salepetronije" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Nikola Vuković", "sterlu" DOTSIGN "sd" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sr_latin[] =
{
  { "mpopovic", "gpopac" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Саша Петровић", "salepetronije" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sv[] =
{
  { "Alexander Nordlund", "deep" DOTSIGN "alexander" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Emil Karlsson", "Emil_1989" ATSIGN "hotmail" DOTSIGN "com", FALSE },
  { "Andreas Rönnquist", "gusnan" ATSIGN "gusnan" DOTSIGN "se", FALSE },
  { "Aksel Bergfeldt", "aksel" DOTSIGN "bergfeldt" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Rickard Larsson", "larsson" ATSIGN "odus" DOTSIGN "se", FALSE },
  { "kim Svensson", "ks" ATSIGN "linux" DOTSIGN "com", FALSE },
  { "Åke Svensson", "webaake" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Elefterios Lundell", "winnie666" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_te[] =
{
  { "Praveen Illa", "mail2ipn" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_th[] =
{
  { "Seksan Neramitthanasombat", "sek" DOTSIGN "cgnz" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_tl[] =
{
  { "Charles Casuga", "charlescasuga" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Manuel Oliva", "oliva" DOTSIGN "manuel" ATSIGN "ymail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_tr[] =
{
  { "Alper Tekinalp", "alper" DOTSIGN "tekinalp" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "gokmen", "gokmen" ATSIGN "alageek" DOTSIGN "com", TRUE },
  { "Necdet Yücel", "necdetyucel" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Adnan Kenar", "akenar06" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Akın Ömeroğlu", "akin" ATSIGN "pardus" DOTSIGN "org" DOTSIGN "tr", FALSE },
  { "Ramazan Gürbüz", "ramazangurbuz" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Avatar", "coskuno_99" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "Aydan Taşdemir", "aydantasdemir" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ayhan YALÇINSOY", "ayhanyalcinsoy" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Caner Çuhac", "ccuhac" ATSIGN "mynet" DOTSIGN "com", FALSE },
  { "Erçin EKER", "ercineker" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Eren Türkay", "erenturkay" ATSIGN "xfce" DOTSIGN "org", FALSE },
  { "Ertuğrul HAZAR", "ertugrulhazar" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Gökhan Kılınç", "kilincgokhan" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Hafzullah", "hafzullah" DOTSIGN "is" ATSIGN "windowslive" DOTSIGN "com", FALSE },
  { "Ilker DAGLI", "ilker" ATSIGN "ilkerdagli" DOTSIGN "info", FALSE },
  { "kozdincer", "kaanozdincer" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Deniz Ogut", "kdenizogut" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "marici", "cadthecoder" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "martinamca", "martinamca" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Murat DOGANCAY", "mdogancay" ATSIGN "gmx" DOTSIGN "net", FALSE },
  { "mesutcank", "", FALSE },
  { "mrtcvk", "muratcevikgs" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Osman Karagöz", "osmank3" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ozan Türkyılmaz", "ozan" DOTSIGN "turkyilmaz" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Özgür Kuru", "ozgur" ATSIGN "ozgurkuru" DOTSIGN "net", FALSE },
  { "Murat PINAR", "wargasm" ATSIGN "archlinux" DOTSIGN "us", FALSE },
  { "Senol Korkmaz", "mail" ATSIGN "senolkorkmaz" DOTSIGN "info", FALSE },
  { "Server Acim", "serveracim" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "skocadogan", "skocadogan" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Utku Berberoğlu", "utku" DOTSIGN "berber" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Utku Aydın", "utkuaydin" ATSIGN "archlinux" DOTSIGN "org" DOTSIGN "tr", FALSE },
  { "vlyalcin", "naklovnak" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_tt[] =
{
  { "Ainur Shakirov", "ainur" DOTSIGN "shakirov" DOTSIGN "tt" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ug[] =
{
  { "Gheyret Kenji", "gheyret" ATSIGN "yahoo" DOTSIGN "com", TRUE },
  { "Abduqadir Abliz", "sahran" ATSIGN "live" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_uk[] =
{
  { "Dmitry Nikitin", "luckas_fb" ATSIGN "mail" DOTSIGN "ru", TRUE },
  { "Alexandr Toorchyn", "ilex" ATSIGN "mail" DOTSIGN "ua", FALSE },
  { "Yarema aka Knedlyk", "yupadmin" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Maxim Dziumanenko", "dziumanenko" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Olexandr Nesterenko", "olexn" ATSIGN "ukr" DOTSIGN "net", FALSE },
  { "Pavlo Bilyak", "jpavlo11" ATSIGN "ukr" DOTSIGN "net", FALSE },
  { "Oleksandr Natalenko", "pfactum" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Roman Zdoryk", "romtsjo" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Andriy Matkovsky", "sidius" DOTSIGN "ua" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "tarabopm", "tarabopm" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ur[] =
{
  { "Irfan Ashraf", "visualrange" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_vi[] =
{
  { "Vinh Nguyen", "kureikain" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "funnysorcerer", "sin" DOTSIGN "trunganh" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Lê Trường An", "pinkyfinger111" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_zh_CN[] =
{
  { "Chipong Luo", "chipong" DOTSIGN "luo" ATSIGN "yahoo" DOTSIGN "com", TRUE },
  { "Hunt Xu", "mhuntxu" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "yjwork", "yjwork" DOTSIGN "xfce" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "cicku", "cickumqt" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Hao Cui", "cuihao" DOTSIGN "leo" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Qianqian Fang", "fangqq" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "haobug", "qinghao1" ATSIGN "foxmail" DOTSIGN "com", FALSE },
  { "Ganghua Leng", "hiweed" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Frank Lee", "lifei" ATSIGN "schaeffler" DOTSIGN "com", FALSE },
  { "Michael Lin", "linmx0130" ATSIGN "163" DOTSIGN "com", FALSE },
  { "Howard Chan", "smartboyhw" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "tuhaihe", "1132321739qq" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "winjeg kong", "winjeg" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_zh_HK[] =
{
  { "Howard Chan", "smartboyhw" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Walter cheuk", "wwycheuk" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_zh_TW[] =
{
  { "Cheng-Chia Tseng", "pswo10680" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Pei Yi Chen", "cpyimail" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "ethan42411", "jrpropo10282003" ATSIGN "yahoo" DOTSIGN "com" DOTSIGN "tw", FALSE },
  { "fanasin", "pswo10680" ATSIGN "hotmail" DOTSIGN "com", FALSE },
  { "Yu-Fu Wu", "wennynnewenny" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ruei-Yuan Lu", "RueiYuan" DOTSIGN "Lu" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "shoting", "shoting" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Howard Chan", "smartboyhw" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Chia-Han Lee", "sonronlee" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Walter cheuk", "wwycheuk" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorTeam xfce_translators[] =
{
  { "Amharic", "am", xfce_translators_am },
  { "Arabic", "ar", xfce_translators_ar },
  { "Asturian", "ast", xfce_translators_ast },
  { "Belarusian", "be", xfce_translators_be },
  { "Bulgarian", "bg", xfce_translators_bg },
  { "Bengali", "bn", xfce_translators_bn },
  { "Bengali (India)", "bn_IN", xfce_translators_bn_IN },
  { "Catalan (Valencian)", "ca", xfce_translators_ca },
  { "Czech", "cs", xfce_translators_cs },
  { "Danish", "da", xfce_translators_da },
  { "German", "de", xfce_translators_de },
  { "Greek", "el", xfce_translators_el },
  { "English (United Kingdom)", "en_GB", xfce_translators_en_GB },
  { "Esperanto", "eo", xfce_translators_eo },
  { "Spanish (Castilian)", "es", xfce_translators_es },
  { "Spanish (Argentinian)", "es_AR", xfce_translators_es_AR },
  { "Estonian", "et", xfce_translators_et },
  { "Basque", "eu", xfce_translators_eu },
  { "Persian", "fa", xfce_translators_fa },
  { "Finnish", "fi", xfce_translators_fi },
  { "French", "fr", xfce_translators_fr },
  { "Galician", "gl", xfce_translators_gl },
  { "Hebrew", "he", xfce_translators_he },
  { "Hindi", "hi", xfce_translators_hi },
  { "Croatian", "hr", xfce_translators_hr },
  { "Hungarian", "hu", xfce_translators_hu },
  { "Armenian", "hy", xfce_translators_hy },
  { "Indonesian", "id", xfce_translators_id },
  { "Icelandic", "is", xfce_translators_is },
  { "Italian", "it", xfce_translators_it },
  { "Japanese", "ja", xfce_translators_ja },
  { "Georgian", "ka", xfce_translators_ka },
  { "Kazakh", "kk", xfce_translators_kk },
  { "Kannada", "kn", xfce_translators_kn },
  { "Korean", "ko", xfce_translators_ko },
  { "Kirgyz", "ky", xfce_translators_ky },
  { "Lithuanian", "lt", xfce_translators_lt },
  { "Latvian", "lv", xfce_translators_lv },
  { "Malay", "ms", xfce_translators_ms },
  { "Norwegian Bokmal", "nb", xfce_translators_nb },
  { "Dutch (Flemish)", "nl", xfce_translators_nl },
  { "Norwegian Nynorsk", "nn", xfce_translators_nn },
  { "Ossetian", "os", xfce_translators_os },
  { "Panjabi (Punjabi)", "pa", xfce_translators_pa },
  { "Polish", "pl", xfce_translators_pl },
  { "Portuguese", "pt", xfce_translators_pt },
  { "Portuguese (Brazilian)", "pt_BR", xfce_translators_pt_BR },
  { "Romanian", "ro", xfce_translators_ro },
  { "Russian", "ru", xfce_translators_ru },
  { "Sinhala", "si", xfce_translators_si },
  { "Slovak", "sk", xfce_translators_sk },
  { "Slovenian", "sl", xfce_translators_sl },
  { "Albanian", "sq", xfce_translators_sq },
  { "Serbian", "sr", xfce_translators_sr },
  { "Serbian (Latin)", "sr@latin", xfce_translators_sr_latin },
  { "Swedish", "sv", xfce_translators_sv },
  { "Telugu", "te", xfce_translators_te },
  { "Thai", "th", xfce_translators_th },
  { "Tagalog", "tl", xfce_translators_tl },
  { "Turkish", "tr", xfce_translators_tr },
  { "Tatar", "tt", xfce_translators_tt },
  { "Uyghur", "ug", xfce_translators_ug },
  { "Ukrainian", "uk", xfce_translators_uk },
  { "Urdu", "ur", xfce_translators_ur },
  { "Vietnamese", "vi", xfce_translators_vi },
  { "Chinese (China)", "zh_CN", xfce_translators_zh_CN },
  { "Chinese (Hong Kong)", "zh_HK", xfce_translators_zh_HK },
  { "Chinese (Taiwan)", "zh_TW", xfce_translators_zh_TW },
};
