/*
 * Copyright (C) 2010 Xfce Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

/*
 * THIS FILE IS AUTOMATICALLY GENERATED BY http://translations.xfce.org
 * DO NOT EDIT IT MANUALLY!
 */

#include <gtk/gtk.h>
#include <libxfce4util/libxfce4util.h>

#define TRANSLATORS_H_STAMP "2011-11-28 17:24:48"
#define ATSIGN "@"
#define DOTSIGN "."

typedef struct
{
  const gchar *name;
  const gchar *email;
  guint        is_coordinator : 1;
}
TranslatorInfo;

typedef struct
{
  const gchar          *name;
  const gchar          *code;
  const TranslatorInfo *members;
}
TranslatorTeam;

static const TranslatorInfo xfce_translators_am[] =
{
  { "Tegegne Tefera", "tefera" ATSIGN "mekuria" DOTSIGN "com", TRUE },
  { "Fantaw Tesema", "fantaw" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ar[] =
{
  { "كريم أولاد الشلحة", "herr" DOTSIGN "linux88" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Hasen il Judy", "hasan" DOTSIGN "aljudy" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "محمد الحرقان", "malham1" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Yassine Bouhadi", "yassine" DOTSIGN "skiloo" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "ybanafa", "ybanafa" ATSIGN "alasersystems" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ast[] =
{
  { "Iñigo Varela", "malditoastur" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_be[] =
{
  { "Andrei Zakharevich", "andrej" ATSIGN "zahar" DOTSIGN "ws", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_bg[] =
{
  { "Valentin Tunev", "hdbuster" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_bn[] =
{
  { "Jamil Ahmed", "itsjamil" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_bn_IN[] =
{
  { "Runa Bhattacharjee", "runabh" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Dipjyoti Ghosh", "dipjyoti" DOTSIGN "ghosh" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sankarshan Mukhopadhyay", "sankarshan" ATSIGN "randomink" DOTSIGN "org", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ca[] =
{
  { "Carles Muñoz Gorriz", "carlesmu" ATSIGN "internautas" DOTSIGN "org", TRUE },
  { "Paul Garden", "kiari62" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jordi Clariana", "jordiclariana" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Roger Pueyo Centelles", "xfce" ATSIGN "rogerpueyo" DOTSIGN "com", FALSE },
  { "Harald Servat", "redcrash" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_cs[] =
{
  { "David Štancl", "dstancl" ATSIGN "dstancl" DOTSIGN "cz", TRUE },
  { "Michal Várady", "miko" DOTSIGN "vaji" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Miro Hrončok", "miro" ATSIGN "hroncok" DOTSIGN "cz", FALSE },
  { "Jakub Špirk", "spirk" DOTSIGN "jakub" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_da[] =
{
  { "Per Kongstad", "p_kongstad" ATSIGN "op" DOTSIGN "pl", TRUE },
  { "Morten Juhl-Johansen Zölde-Fejér", "mjjzf" ATSIGN "syntaktisk" DOTSIGN "dk", FALSE },
  { "tbesand", "thomas" DOTSIGN "besand" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_de[] =
{
  { "Christoph Wickert", "christoph" DOTSIGN "wickert" ATSIGN "googlemail" DOTSIGN "com", TRUE },
  { "Andreas Kamzol", "andreas" DOTSIGN "kamzol" ATSIGN "googlemail" DOTSIGN "com", FALSE },
  { "Christoph Mende", "angelos" ATSIGN "gentoo" DOTSIGN "org", FALSE },
  { "Michael Spahn", "any0n3" ATSIGN "fedoraproject" DOTSIGN "org", FALSE },
  { "Christian Weiske", "cweiske" ATSIGN "cweiske" DOTSIGN "de", FALSE },
  { "Uwe Krause", "derhorst" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jakob Kramer", "jakob" DOTSIGN "kramer" ATSIGN "gmx" DOTSIGN "de", FALSE },
  { "Johannes Lips", "johannes" DOTSIGN "lips" ATSIGN "googlemail" DOTSIGN "com", FALSE },
  { "Hubert Hesse", "hub" ATSIGN "hubertscorner" DOTSIGN "de", FALSE },
  { "Mark Trompell", "mark" ATSIGN "foresightlinux" DOTSIGN "org", FALSE },
  { "Matthias Mailänder", "matthias" ATSIGN "mailaender" DOTSIGN "name", FALSE },
  { "Michael Schmitt", "user" DOTSIGN "of" DOTSIGN "xfce" ATSIGN "googlemail" DOTSIGN "com", FALSE },
  { "Niklas Reinmuth", "Niklas" DOTSIGN "Reinmuth" ATSIGN "googlemail" DOTSIGN "com", FALSE },
  { "Paul Seyfert", "pseyfert" ATSIGN "mathphys" DOTSIGN "fsk" DOTSIGN "uni-heidelberg" DOTSIGN "de", FALSE },
  { "Knuth Gurkasch", "knuth" ATSIGN "sinn3r" DOTSIGN "org", FALSE },
  { "Fabian Nowak", "timystery" ATSIGN "arcor" DOTSIGN "de", FALSE },
  { "Detlef Riekenberg", "wine" DOTSIGN "dev" ATSIGN "web" DOTSIGN "de", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_el[] =
{
  { "Evaggelos Balaskas", "ebalaskas" ATSIGN "ebalaskas" DOTSIGN "gr", TRUE },
  { "Stavros Giannouris", "stavrosg" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Ioannis Daliakopoulos", "yannis" ATSIGN "farm" DOTSIGN "gr", FALSE },
  { "forfolias", "forfolias" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "gapan", "vlahavas" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "jemadux", "kleagkou" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Mario Andonoudiou", "supermodmusic" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Spiros Georgaras", "sng" ATSIGN "hellug" DOTSIGN "gr", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_en_GB[] =
{
  { "Jeff Bailes", "thepizzaking" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_eo[] =
{
  { "Michael Moroni", "michael" DOTSIGN "moroni" ATSIGN "mailoo" DOTSIGN "org", TRUE },
  { "Jakob Pedersen", "jakobp78" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Aleksandr Ponomarenko", "davian818" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_es[] =
{
  { "Andres Sanchez", "afsanchez93" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Abel Martín", "abel" DOTSIGN "martin" DOTSIGN "ruiz" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Javier Sánchez Reinosa", "donoban" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ignacio Velasco", "elega" ATSIGN "elega" DOTSIGN "com" DOTSIGN "ar", FALSE },
  { "Esteban Vidal González", "esteban70x7" ATSIGN "yahoo" DOTSIGN "es", FALSE },
  { "Adolfo Jayme Barrientos", "fitoschido" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "José Ángel Alonso", "landseerstreet" ATSIGN "yahoo" DOTSIGN "it", FALSE },
  { "Francisco Rossi", "pupi_8888" ATSIGN "hotmail" DOTSIGN "com", FALSE },
  { "vtamara", "vtamara" ATSIGN "pasosdeJesus" DOTSIGN "org", FALSE },
  { "Gonzalo Lagos", "xalo" DOTSIGN "em" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_es_AR[] =
{
  { "Diego Augusto Molina", "diegoaugustomolina" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Santiago Quiroga", "santiago" DOTSIGN "j" DOTSIGN "quiroga" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "vtamara", "vtamara" ATSIGN "pasosdeJesus" DOTSIGN "org", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_et[] =
{
  { "Allar Kiristaja", "aquastus" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_eu[] =
{
  { "Piarres Beobide", "pi" ATSIGN "beobide" DOTSIGN "net", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_fa[] =
{
  { "Mehdi Esmaeelpour", "ariarat" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ehsan Akhlaghi", "esnka" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_fi[] =
{
  { "Jari Rahkonen", "jari" DOTSIGN "rahkonen" ATSIGN "pp1" DOTSIGN "inet" DOTSIGN "fi", TRUE },
  { "Jarno Liimatainen", "jarliim" ATSIGN "iki" DOTSIGN "fi", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_fr[] =
{
  { "Xavier Devlamynck", "magicrhesus" ATSIGN "ouranos" DOTSIGN "be", TRUE },
  { "Mike Massonnet", "mmassonnet" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Durand-Favreau Arnaud", "biginoz" ATSIGN "free" DOTSIGN "fr", FALSE },
  { "Mario Gervais", "gervais" DOTSIGN "mario" ATSIGN "ymail" DOTSIGN "com", FALSE },
  { "Jérôme Guelfucci", "jeromeg" ATSIGN "xfce" DOTSIGN "org", FALSE },
  { "Jean-Philippe Fleury", "contact" ATSIGN "jpfleury" DOTSIGN "net", FALSE },
  { "Jourdain Cyril", "cyril" DOTSIGN "jd" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Louis M", "m_louis30" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "Maximilian Schleiss", "maximilian" ATSIGN "xfce" DOTSIGN "org", FALSE },
  { "marc doutreloux", "mdoutreloux" ATSIGN "yahoo" DOTSIGN "fr", FALSE },
  { "Pardaigle", "worldmania" ATSIGN "free" DOTSIGN "fr", FALSE },
  { "douart patrick", "patrick" DOTSIGN "2" ATSIGN "laposte" DOTSIGN "net", FALSE },
  { "Anthony Jorion", "pingax" ATSIGN "frugalware" DOTSIGN "fr", FALSE },
  { "Steve Dodier", "sidnioulz" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_gl[] =
{
  { "Leandro Regueiro", "leandro" DOTSIGN "regueiro" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_he[] =
{
  { "Yaron Shahrabani", "sh" DOTSIGN "yaron" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Hezy Amiel", "open" ATSIGN "hezyamiel" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_hi[] =
{
  { "Anurag Garg", "ang" DOTSIGN "astronomy" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_hr[] =
{
  { "Petar Koretić", "petar" DOTSIGN "koretic" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Ivica Kolić", "ikoli" ATSIGN "yahoo" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_hu[] =
{
  { "Gabor Kelemen", "kelemeng" ATSIGN "gnome" DOTSIGN "hu", TRUE },
  { "Zelenak Sandor", "nem11nator" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_hy[] =
{
  { "sssilver", "sssilver" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_id[] =
{
  { "Andhika Padmawan", "andhika" DOTSIGN "padmawan" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Ardjuna", "ard_h_r" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "zaenal1234", "zaenal1234" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_is[] =
{
  { "sveinki", "sveinki" ATSIGN "nett" DOTSIGN "is", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_it[] =
{
  { "gianluca foddis", "gianluca" DOTSIGN "foddis" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Giuseppe D'Andrea", "cryptstudent" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "Leonardo Totaro", "elleti" DOTSIGN "brainvision" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Cristian Marchi", "cri" DOTSIGN "penta" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Cristian Cozzolino", "cristiancozzolino" ATSIGN "libero" DOTSIGN "it", FALSE },
  { "maluc", "incjsp" ATSIGN "yahoo" DOTSIGN "it", FALSE },
  { "Riccardo Magini", "rcrmgn" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergio Spinatelli", "eseasonsapp" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ja[] =
{
  { "Masato Hashimoto", "hashimo" ATSIGN "xfce" DOTSIGN "org", TRUE },
  { "Nobuhiro Iwamatsu", "iwamatsu" ATSIGN "nigauri" DOTSIGN "org", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_kk[] =
{
  { "Bauzhan Muftakhidinov", "baurthefirst" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_kn[] =
{
  { "shankar", "prasad" DOTSIGN "mvs" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Vasudev Kamath", "kamathvasudev" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ko[] =
{
  { "Boram Kim", "boramism" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Seong-ho Cho", "darkcircle" DOTSIGN "0426" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "ByungHyun Choi", "byunghyun" DOTSIGN "choi" ATSIGN "live" DOTSIGN "com", FALSE },
  { "Sung Jin Gang", "ujuc" ATSIGN "ujuc" DOTSIGN "kr", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_lt[] =
{
  { "Ričardas Vasiulis", "ricardas" DOTSIGN "v" ATSIGN "inbox" DOTSIGN "lt", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_lv[] =
{
  { "Rihards Prieditis", "rprieditis" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ms[] =
{
  { "megavarnan", "mega_rhujung" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "Mohd" DOTSIGN " Nadzrin Sapari", "terjemah" DOTSIGN "puretech" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_nb[] =
{
  { "Terje Uriansrud", "terje" ATSIGN "uriansrud" DOTSIGN "net", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_nl[] =
{
  { "Nick Schermer", "nick" ATSIGN "xfce" DOTSIGN "org", TRUE },
  { "padv", "pascal" DOTSIGN "devuyst" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Pjotr Anon", "pliniusminor" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Robin Jacobs", "broederjacobs" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Timo Verbeek", "timoverbeek10" ATSIGN "hotmail" DOTSIGN "com", FALSE },
  { "Vincent Tunru", "projects" ATSIGN "vinnl" DOTSIGN "nl", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_nn[] =
{
  { "Eskild Hustvedt", "user" ATSIGN "zerodogg" DOTSIGN "org", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_pa[] =
{
  { "A S Alam", "apreet" DOTSIGN "alam" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_pl[] =
{
  { "Piotr Sokół", "psokol" ATSIGN "jabster" DOTSIGN "pl", TRUE },
  { "Paweł Drożański", "pawdro" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Kamil Polczak", "elderlinx" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ireneusz Gierlach", "irek" DOTSIGN "gierlach" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "jacek2v", "jacek2v" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jakub Waśko", "javazlaz" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Michał Olber", "michal" DOTSIGN "olber" ATSIGN "osworld" DOTSIGN "pl", FALSE },
  { "Jeremy Nicolas", "jerekpl" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Tomasz Chudyk", "chudyk" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_pt[] =
{
  { "Nuno Miguel", "nunis" ATSIGN "netcabo" DOTSIGN "pt", TRUE },
  { "Bruno Ramos", "brunoramos" DOTSIGN "lu" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Joel Patrão", "joel" DOTSIGN "patrao" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergio Marques", "smarquespt" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_pt_BR[] =
{
  { "Henrique P" DOTSIGN " Machado", "zehrique" ATSIGN "xfce" DOTSIGN "org", TRUE },
  { "André Luiz Dias de Miranda", "andreldm1989" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Mateus Rodrigues Costa", "charles" DOTSIGN "costar" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Douglas Sales", "doug" DOTSIGN "sales23" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Frederico Schardong", "frede" DOTSIGN "sch" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Job Borges", "jobdiogenes" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Jonas agx", "jonas" DOTSIGN "agx" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Joelso Andrade", "kosmofilo" ATSIGN "ymail" DOTSIGN "com", FALSE },
  { "Michel Boaventura", "michel" DOTSIGN "boaventura" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Rafael Neri", "rafepel" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Filipe Rosset", "rosset" DOTSIGN "filipe" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sérgio Cipolla", "secipolla" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Tomas Schertel", "tschertel" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Vladimir Melo", "vladimirmelo" DOTSIGN "psi" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Michael Martins", "michaelfm21" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ro[] =
{
  { "Mișu Moldovan", "dumol" ATSIGN "xfce" DOTSIGN "org", TRUE },
  { "Andrei Popescu", "andreimpopescu" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergiu Mihai", "sergiu" DOTSIGN "mihai" ATSIGN "devlibre" DOTSIGN "net", FALSE },
  { "razvan86", "florinrazvan1986" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Mihai Coman", "mihai" ATSIGN "m1x" DOTSIGN "ro", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ru[] =
{
  { "Dmitrij Smirnov", "other" ATSIGN "igus" DOTSIGN "lv", TRUE },
  { "0leg", "s" ATSIGN "0leg" DOTSIGN "me", FALSE },
  { "Anton Batenev", "antonbatenev" ATSIGN "yandex" DOTSIGN "ru", FALSE },
  { "Alexandr Boltris", "ua2fgb" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Alexander Yashkin", "alex" DOTSIGN "aspirine" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Artem Zolochevskiy", "artem" DOTSIGN "zolochevskiy" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Claque", "cpt-alatriste" ATSIGN "ya" DOTSIGN "ru", FALSE },
  { "dkorzhevin", "dkorzhevin" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Evgeniy Kosov", "eugene" ATSIGN "kosov" DOTSIGN "net", FALSE },
  { "gnulinux", "nazarov-1990" ATSIGN "bk" DOTSIGN "ru", FALSE },
  { "Vlad Vasilev", "lortwer" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Alexander Matveyev", "a" DOTSIGN "s" DOTSIGN "matveyev" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Denis Koryavov", "dkoryavov" ATSIGN "yandex" DOTSIGN "ru", FALSE },
  { "Andres Kovtunos", "kovtunos" ATSIGN "yandex" DOTSIGN "ru", FALSE },
  { "Avgustine McDonald", "crispsandchees" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Dmitriy Kudryashov", "overmailed" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergiu Mihai", "sergiu" DOTSIGN "mihai" ATSIGN "devlibre" DOTSIGN "net", FALSE },
  { "Sergey Abramkin", "sergey" ATSIGN "abramk" DOTSIGN "in", FALSE },
  { "Leonid Eremin", "pan" DOTSIGN "sandurlay" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergey Davidoff", "shnatsel" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Sergey Fedoseev", "fedoseev" DOTSIGN "sergey" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Styopa Semenukha", "semenukha" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "ton", "tonawuda" ATSIGN "inbox" DOTSIGN "ru", FALSE },
  { "Aleksandr Ponomarenko", "davian818" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ivan Nikolaev", "voidexp" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Victor Homyakov", "homyakov" ATSIGN "isida" DOTSIGN "by", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_si[] =
{
  { "Danishka Navin", "danishka" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Akila Wajirasena", "akila" DOTSIGN "wajirasena" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Anandawardhana", "anandawardhana" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Kalpa Pathum Welivitigoda", "callkalpa" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Prabath Galagamage", "gprabath" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "kasundigital", "kasunindika" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "kpgtharaka", "kpgtharaka" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "rashan", "rashan" DOTSIGN "uoc" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sk[] =
{
  { "Robert Hartl", "hartl" DOTSIGN "robert" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Michal Löffler", "lofflermichalloffler" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Peter Bubelíny", "p" DOTSIGN "bubeliny" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "ecube", "machava" DOTSIGN "b" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Marek Hlava", "headsvk" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "komunista", "linux" ATSIGN "slavino" DOTSIGN "sk", FALSE },
  { "Tomáš Vadina", "kyberdev" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Tomáš Fedaš", "fedas" DOTSIGN "tomas" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sl[] =
{
  { "Alan Pepelko", "alan" DOTSIGN "pepelko" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Gašper Tomažič", "gasper" ATSIGN "gmx" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sq[] =
{
  { "Besnik Bleta", "besnik" ATSIGN "programeshqip" DOTSIGN "org", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sr[] =
{
  { "Milan Stojakov", "koleramilan" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Мирослав Николић", "miroslavnikolic" ATSIGN "rocketmail" DOTSIGN "com", FALSE },
  { "mpopovic", "gpopac" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Nikola Milosavljevic", "minikola" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sr_latin[] =
{
  { "mpopovic", "gpopac" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_sv[] =
{
  { "Daniel Nylander", "po" ATSIGN "danielnylander" DOTSIGN "se", TRUE },
  { "Alexander Nordlund", "deep" DOTSIGN "alexander" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Emil Karlsson", "Emil_1989" ATSIGN "hotmail" DOTSIGN "com", FALSE },
  { "kim Svensson", "ks6g10" ATSIGN "soton" DOTSIGN "ac" DOTSIGN "uk", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ta[] =
{
  { "megavarnan", "mega_rhujung" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "Mohan R", "mohan43u" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_te[] =
{
  { "Praveen Illa", "mail2ipn" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_tl[] =
{
  { "Manuel Oliva", "oliva" DOTSIGN "manuel" ATSIGN "ymail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_tr[] =
{
  { "Alper Tekinalp", "alper" DOTSIGN "tekinalp" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "gokmen", "gokmen" ATSIGN "alageek" DOTSIGN "com", TRUE },
  { "necdetyucel", "necdetyucel" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Akın Ömeroğlu", "akin" ATSIGN "pardus" DOTSIGN "org" DOTSIGN "tr", FALSE },
  { "Avatar", "coskuno_99" ATSIGN "yahoo" DOTSIGN "com", FALSE },
  { "Aydan Taşdemir", "aydantasdemir" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ayhan YALÇINSOY", "ayhanyalcinsoy" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Caner Gural", "cgural" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Erçin EKER", "ercineker" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Eren Türkay", "erenturkay" ATSIGN "xfce" DOTSIGN "org", FALSE },
  { "Ertuğrul HAZAR", "ertugrulhazar" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Gökhan Kılınç", "kilincgokhan" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Hafzullah", "hafzullah" DOTSIGN "is" ATSIGN "windowslive" DOTSIGN "com", FALSE },
  { "Ilker DAGLI", "ilker" ATSIGN "ilkerdagli" DOTSIGN "info", FALSE },
  { "kozdincer", "kaanozdincer" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Deniz Ogut", "kdenizogut" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "marici", "cadthecoder" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "martinamca", "martinamca" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Murat DOGANCAY", "mdogancay" ATSIGN "gmx" DOTSIGN "net", FALSE },
  { "mesutcank", "mesutcank" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "mrtcvk", "muratcevikgs" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Osman Karagöz", "osmank3" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ozan Türkyılmaz", "ozan" DOTSIGN "turkyilmaz" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Özgür Kuru", "ozgur" ATSIGN "ozgurkuru" DOTSIGN "net", FALSE },
  { "Murat PINAR", "wargasm" ATSIGN "archlinux" DOTSIGN "us", FALSE },
  { "Samed Beyribey", "beyribey" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Senol Korkmaz", "mail" ATSIGN "senolkorkmaz" DOTSIGN "info", FALSE },
  { "Server Acim", "serveracim" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "skocadogan", "skocadogan" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Utku Aydın", "utkuaydin" ATSIGN "archlinux" DOTSIGN "org" DOTSIGN "tr", FALSE },
  { "vlyalcin", "naklovnak" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_tt[] =
{
  { "Ainur Shakirov", "ainur" DOTSIGN "shakirov" DOTSIGN "tt" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ug[] =
{
  { "Gheyret Kenji", "gheyret" ATSIGN "yahoo" DOTSIGN "com", TRUE },
  { "Abduqadir Abliz", "sahran" ATSIGN "live" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_uk[] =
{
  { "Dmitry Nikitin", "luckas_fb" ATSIGN "mail" DOTSIGN "ru", TRUE },
  { "Yarema aka Knedlyk", "yupadmin" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Maxim Dziumanenko", "dziumanenko" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "olexandrN", "olexn" ATSIGN "ukr" DOTSIGN "net", FALSE },
  { "Oleksandr Natalenko", "pfactum" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Andriy Matkovsky", "sidius" DOTSIGN "ua" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "tarabopm", "tarabopm" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_ur[] =
{
  { "Irfan Ashraf", "visualrange" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_vi[] =
{
  { "Vinh Nguyen", "kureikain" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "funnysorcerer", "sin" DOTSIGN "trunganh" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_zh_CN[] =
{
  { "Chipong Luo", "chipong_l" ATSIGN "yahoo" DOTSIGN "com", TRUE },
  { "Hunt Xu", "mhuntxu" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "玉堂 白鹤", "yjwork" DOTSIGN "xfce" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "Hao Cui", "cuihao" DOTSIGN "leo" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Qianqian Fang", "fangqq" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "Ganghua Leng", "hiweed" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { "xsoul", "", FALSE },
  { NULL, NULL }
};

static const TranslatorInfo xfce_translators_zh_TW[] =
{
  { "Cheng-Chia Tseng", "pswo10680" ATSIGN "gmail" DOTSIGN "com", TRUE },
  { "fanasin", "pswo10680" ATSIGN "hotmail" DOTSIGN "com", FALSE },
  { "Chia-Han Lee", "gloomysaga" ATSIGN "gmail" DOTSIGN "com", FALSE },
  { NULL, NULL }
};

static const TranslatorTeam xfce_translators[] =
{
  { "Amharic", "am", xfce_translators_am },
  { "Arabic", "ar", xfce_translators_ar },
  { "Asturian", "ast", xfce_translators_ast },
  { "Belarusian", "be", xfce_translators_be },
  { "Bulgarian", "bg", xfce_translators_bg },
  { "Bengali", "bn", xfce_translators_bn },
  { "Bengali (India)", "bn_IN", xfce_translators_bn_IN },
  { "Catalan (Valencian)", "ca", xfce_translators_ca },
  { "Czech", "cs", xfce_translators_cs },
  { "Danish", "da", xfce_translators_da },
  { "German", "de", xfce_translators_de },
  { "Greek", "el", xfce_translators_el },
  { "English (United Kingdom)", "en_GB", xfce_translators_en_GB },
  { "Esperanto", "eo", xfce_translators_eo },
  { "Spanish (Castilian)", "es", xfce_translators_es },
  { "Spanish (Argentinian)", "es_AR", xfce_translators_es_AR },
  { "Estonian", "et", xfce_translators_et },
  { "Basque", "eu", xfce_translators_eu },
  { "Persian", "fa", xfce_translators_fa },
  { "Finnish", "fi", xfce_translators_fi },
  { "French", "fr", xfce_translators_fr },
  { "Galician", "gl", xfce_translators_gl },
  { "Hebrew", "he", xfce_translators_he },
  { "Hindi", "hi", xfce_translators_hi },
  { "Croatian", "hr", xfce_translators_hr },
  { "Hungarian", "hu", xfce_translators_hu },
  { "Armenian", "hy", xfce_translators_hy },
  { "Indonesian", "id", xfce_translators_id },
  { "Icelandic", "is", xfce_translators_is },
  { "Italian", "it", xfce_translators_it },
  { "Japanese", "ja", xfce_translators_ja },
  { "Kazakh", "kk", xfce_translators_kk },
  { "Kannada", "kn", xfce_translators_kn },
  { "Korean", "ko", xfce_translators_ko },
  { "Lithuanian", "lt", xfce_translators_lt },
  { "Latvian", "lv", xfce_translators_lv },
  { "Malay", "ms", xfce_translators_ms },
  { "Norwegian Bokmal", "nb", xfce_translators_nb },
  { "Dutch (Flemish)", "nl", xfce_translators_nl },
  { "Norwegian Nynorsk", "nn", xfce_translators_nn },
  { "Panjabi (Punjabi)", "pa", xfce_translators_pa },
  { "Polish", "pl", xfce_translators_pl },
  { "Portuguese", "pt", xfce_translators_pt },
  { "Portuguese (Brazilian)", "pt_BR", xfce_translators_pt_BR },
  { "Romanian", "ro", xfce_translators_ro },
  { "Russian", "ru", xfce_translators_ru },
  { "Sinhala", "si", xfce_translators_si },
  { "Slovak", "sk", xfce_translators_sk },
  { "Slovenian", "sl", xfce_translators_sl },
  { "Albanian", "sq", xfce_translators_sq },
  { "Serbian", "sr", xfce_translators_sr },
  { "Serbian (Latin)", "sr@latin", xfce_translators_sr_latin },
  { "Swedish", "sv", xfce_translators_sv },
  { "Tamil", "ta", xfce_translators_ta },
  { "Telugu", "te", xfce_translators_te },
  { "Tagalog", "tl", xfce_translators_tl },
  { "Turkish", "tr", xfce_translators_tr },
  { "Tatar", "tt", xfce_translators_tt },
  { "Uyghur", "ug", xfce_translators_ug },
  { "Ukrainian", "uk", xfce_translators_uk },
  { "Urdu", "ur", xfce_translators_ur },
  { "Vietnamese", "vi", xfce_translators_vi },
  { "Chinese (China)", "zh_CN", xfce_translators_zh_CN },
  { "Chinese (Taiwan)", "zh_TW", xfce_translators_zh_TW },
};
